import { Product } from "./types";

export const products: Product[] = [
  {
    id: "0",
    title: "Syltherine",
    description: "Stylish cafe chair",
    currency: "Rp",
    price: 3500000,
    discountPercent: 30,
    image: "image-1.webp",
    isNew: false,
  },
  {
    id: "1",
    title: "Leviosa",
    description: "Indoor plant pot",
    currency: "Rp",
    price: 2500000,
    discountPercent: null,
    image: "image-2.webp",
    isNew: false,
  },
  {
    id: "2",
    title: "Lolito",
    description: "Luxury big sofa",
    currency: "Rp",
    price: 14000000,
    discountPercent: 50,
    image: "image-3.webp",
    isNew: false,
  },
  {
    id: "3",
    title: "Respira",
    description: "Outdoor bar table and stool",
    currency: "Rp",
    price: 500000,
    discountPercent: null,
    image: "image-4.webp",
    isNew: true,
  },
  {
    id: "4",
    title: "Grifo",
    description: "Night lamp",
    currency: "Rp",
    price: 1500000,
    discountPercent: null,
    image: "image-5.webp",
    isNew: false,
  },
  {
    id: "5",
    title: "Muggo",
    description: "Small mug",
    currency: "Rp",
    price: 150000,
    discountPercent: null,
    image: "image-6.webp",
    isNew: true,
  },
  {
    id: "6",
    title: "Pingky",
    description: "Cute bed set",
    currency: "Rp",
    price: 14000000,
    discountPercent: 50,
    image: "image-7.webp",
    isNew: true,
  },
  {
    id: "7",
    title: "Potty",
    description: "Minimalist flower pot",
    currency: "Rp",
    price: 500000,
    discountPercent: null,
    image: "image-8.webp",
    isNew: true,
  },
  {
    id: "8",
    title: "Grifo",
    description: "Night lamp",
    currency: "Rp",
    price: 1500000,
    discountPercent: null,
    image: "image-9.webp",
    isNew: false,
  },
  {
    id: "9",
    title: "Furnito",
    description: "Elegant office chair",
    currency: "Rp",
    price: 3200000,
    discountPercent: 10,
    image: "image-10.jpeg",
    isNew: true,
  },
  {
    id: "10",
    title: "Planto",
    description: "Decorative indoor plant",
    currency: "Rp",
    price: 600000,
    discountPercent: null,
    image: "image-11.jpeg",
    isNew: false,
  },
  {
    id: "11",
    title: "Windo",
    description: "Modern window blinds",
    currency: "Rp",
    price: 800000,
    discountPercent: null,
    image: "image-12.jpeg",
    isNew: true,
  },
  {
    id: "12",
    title: "Cuppa",
    description: "Classic tea cup set",
    currency: "Rp",
    price: 450000,
    discountPercent: 20,
    image: "image-13.jpeg",
    isNew: false,
  },
  {
    id: "13",
    title: "Tablo",
    description: "Vintage wooden table",
    currency: "Rp",
    price: 5500000,
    discountPercent: null,
    image: "image-14.jpeg",
    isNew: true,
  },
  {
    id: "14",
    title: "Cushy",
    description: "Soft throw pillow",
    currency: "Rp",
    price: 300000,
    discountPercent: null,
    image: "image-15.jpeg",
    isNew: false,
  },
  {
    id: "15",
    title: "Artsy",
    description: "Abstract art painting",
    currency: "Rp",
    price: 2000000,
    discountPercent: 5,
    image: "image-4.webp",
    isNew: true,
  },
  {
    id: "16",
    title: "Lumina",
    description: "Modern floor lamp",
    currency: "Rp",
    price: 1700000,
    discountPercent: null,
    image: "image-5.webp",
    isNew: false,
  },
  {
    id: "17",
    title: "Vasey",
    description: "Ceramic flower vase",
    currency: "Rp",
    price: 450000,
    discountPercent: null,
    image: "image-6.webp",
    isNew: true,
  },
  {
    id: "18",
    title: "Globy",
    description: "Globe-shaped hanging light",
    currency: "Rp",
    price: 1250000,
    discountPercent: 15,
    image: "image-7.webp",
    isNew: false,
  },
  {
    id: "19",
    title: "Sitty",
    description: "Ergonomic office stool",
    currency: "Rp",
    price: 2200000,
    discountPercent: null,
    image: "image-8.webp",
    isNew: true,
  },
  {
    id: "20",
    title: "Boardy",
    description: "Wooden cutting board",
    currency: "Rp",
    price: 350000,
    discountPercent: null,
    image: "image-9.webp",
    isNew: false,
  },
  {
    id: "21",
    title: "Cozy",
    description: "Comfortable reading chair",
    currency: "Rp",
    price: 2900000,
    discountPercent: null,
    image: "image-10.jpeg",
    isNew: true,
  },
  {
    id: "22",
    title: "Writty",
    description: "Vintage writing desk",
    currency: "Rp",
    price: 4800000,
    discountPercent: null,
    image: "image-11.jpeg",
    isNew: false,
  },
  {
    id: "23",
    title: "Comfy",
    description: "Soft cotton bed sheets",
    currency: "Rp",
    price: 700000,
    discountPercent: null,
    image: "image-12.jpeg",
    isNew: true,
  },
  {
    id: "21",
    title: "Cozy",
    description: "Comfortable reading chair",
    currency: "Rp",
    price: 2900000,
    discountPercent: null,
    image: "image-13.jpeg",
    isNew: true,
  },
  {
    id: "22",
    title: "Writty",
    description: "Vintage writing desk",
    currency: "Rp",
    price: 4800000,
    discountPercent: null,
    image: "image-14.jpeg",
    isNew: false,
  },
  {
    id: "23",
    title: "Comfy",
    description: "Soft cotton bed sheets",
    currency: "Rp",
    price: 700000,
    discountPercent: null,
    image: "image-15.jpeg",
    isNew: true,
  },
  {
    id: "24",
    title: "Snug",
    description: "Warm winter blanket",
    currency: "Rp",
    price: 1100000,
    discountPercent: 20,
    image: "image-1.webp",
    isNew: false,
  },
  {
    id: "25",
    title: "Orna",
    description: "Decorative wall ornament",
    currency: "Rp",
    price: 600000,
    discountPercent: null,
    image: "image-2.webp",
    isNew: true,
  },
  {
    id: "26",
    title: "Pillowise",
    description: "Memory foam pillow",
    currency: "Rp",
    price: 400000,
    discountPercent: null,
    image: "image-3.webp",
    isNew: false,
  },
  {
    id: "27",
    title: "Brighty",
    description: "LED desk lamp",
    currency: "Rp",
    price: 850000,
    discountPercent: null,
    image: "image-4.webp",
    isNew: true,
  },
  {
    id: "28",
    title: "Shelfy",
    description: "Wall-mounted shelf",
    currency: "Rp",
    price: 1500000,
    discountPercent: null,
    image: "image-5.webp",
    isNew: false,
  },
  {
    id: "29",
    title: "Coasterly",
    description: "Set of coasters",
    currency: "Rp",
    price: 200000,
    discountPercent: null,
    image: "image-6.webp",
    isNew: true,
  },
  {
    id: "30",
    title: "Framey",
    description: "Picture frame set",
    currency: "Rp",
    price: 500000,
    discountPercent: null,
    image: "image-7.webp",
    isNew: false,
  },
  {
    id: "31",
    title: "Clocky",
    description: "Antique wall clock",
    currency: "Rp",
    price: 1250000,
    discountPercent: null,
    image: "image-8.webp",
    isNew: true,
  },
  {
    id: "32",
    title: "Ruggy",
    description: "Handwoven area rug",
    currency: "Rp",
    price: 3000000,
    discountPercent: null,
    image: "image-9.webp",
    isNew: false,
  },
  {
    id: "33",
    title: "Muggy",
    description: "Ceramic mug collection",
    currency: "Rp",
    price: 450000,
    discountPercent: null,
    image: "image-10.jpeg",
    isNew: true,
  },
  {
    id: "34",
    title: "Decory",
    description: "Home decor set",
    currency: "Rp",
    price: 2500000,
    discountPercent: null,
    image: "image-11.jpeg",
    isNew: false,
  },
  {
    id: "35",
    title: "Blanky",
    description: "Fleece blanket",
    currency: "Rp",
    price: 800000,
    discountPercent: null,
    image: "image-12.jpeg",
    isNew: true,
  },
  {
    id: "36",
    title: "Planty",
    description: "Indoor plant pot",
    currency: "Rp",
    price: 300000,
    discountPercent: null,
    image: "image-13.jpeg",
    isNew: false,
  },
  {
    id: "37",
    title: "Sofy",
    description: "Two-seater sofa",
    currency: "Rp",
    price: 7500000,
    discountPercent: null,
    image: "image-14.jpeg",
    isNew: true,
  },
  {
    id: "38",
    title: "Candy",
    description: "Assorted candy jar",
    currency: "Rp",
    price: 250000,
    discountPercent: null,
    image: "image-15.jpeg",
    isNew: false,
  },
  {
    id: "39",
    title: "Cushy",
    description: "Decorative cushion cover",
    currency: "Rp",
    price: 350000,
    discountPercent: null,
    image: "image-1.webp",
    isNew: true,
  },
  {
    id: "40",
    title: "Lampy",
    description: "Stylish table lamp",
    currency: "Rp",
    price: 950000,
    discountPercent: null,
    image: "image-2.webp",
    isNew: false,
  },
  {
    id: "41",
    title: "Arty",
    description: "Contemporary art piece",
    currency: "Rp",
    price: 4600000,
    discountPercent: null,
    image: "image-3.webp",
    isNew: true,
  },
  {
    id: "42",
    title: "Vasey",
    description: "Elegant flower vase",
    currency: "Rp",
    price: 550000,
    discountPercent: null,
    image: "image-4.webp",
    isNew: false,
  },
  {
    id: "43",
    title: "Booky",
    description: "Leather-bound notebook",
    currency: "Rp",
    price: 300000,
    discountPercent: null,
    image: "image-5.webp",
    isNew: true,
  },
  {
    id: "44",
    title: "Cuppy",
    description: "Set of teacups",
    currency: "Rp",
    price: 450000,
    discountPercent: null,
    image: "image-6.webp",
    isNew: false,
  },
  {
    id: "45",
    title: "Drapy",
    description: "Luxury drapes",
    currency: "Rp",
    price: 1250000,
    discountPercent: null,
    image: "image-7.webp",
    isNew: true,
  },
  {
    id: "46",
    title: "Fruity",
    description: "Fruit bowl centerpiece",
    currency: "Rp",
    price: 650000,
    discountPercent: null,
    image: "image-8.webp",
    isNew: false,
  },
  {
    id: "47",
    title: "Glassy",
    description: "Crystal wine glasses set",
    currency: "Rp",
    price: 1200000,
    discountPercent: null,
    image: "image-9.webp",
    isNew: true,
  },
  {
    id: "48",
    title: "Knitty",
    description: "Hand-knitted throw blanket",
    currency: "Rp",
    price: 900000,
    discountPercent: null,
    image: "image-10.jpeg",
    isNew: false,
  },
  {
    id: "49",
    title: "Lighty",
    description: "Modern chandelier",
    currency: "Rp",
    price: 2000000,
    discountPercent: null,
    image: "image-10.jpeg",
    isNew: true,
  },
  {
    id: "50",
    title: "Mirrory",
    description: "Ornate mirror",
    currency: "Rp",
    price: 1500000,
    discountPercent: null,
    image: "image-11.jpeg",
    isNew: false,
  },
];

export const getProducts = async ({
  count,
  from,
}: {
  count: number;
  from?: number;
}) => {
  const finalProducts = products.slice(from || 0, from ? from + count : count);
  return finalProducts;
};
